---
# include vault vars
- include_vars: linode.yml

- name: spin up new linode via local action
  linode_v4:
    access_token: "{{ vault_linode_token }}"
    label: "{{ new_linode_label }}"
    type: g6-nanode-1
    region: ap-south
    image: linode/debian10
    root_pass: "{{ vault_linode_hostpasswd }}"
    authorized_keys:
      - "{{ vault_linode_ssh_key }}"
    state: present
  delegate_to: 127.0.0.1
  register: newlinode

- name: Display all variables/facts known for linode
  debug:
    var: hostvars[newlinode]

- name: add linode to inventory
  add_host: name="{{ newlinode.instance.ipv4[0] }}" groups=new_linode

- name: Wait for SSH to come up
  local_action: wait_for host="{{ newlinode.instance.ipv4[0] }}" port=22 delay=60 timeout=320 state=started
